- name: Deploy app to Minikube on EC2-B using Docker Hub image
  hosts: minikube
  become: yes
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:

    - name: Copy Kubernetes deployment file
      copy:
        src: /var/lib/jenkins/.jenkins/workspace/Jenkins-ansible-K8s/kubernetes/deploy.yaml
        dest: /home/ec2-user/deployment.yaml

    - name: Apply Kubernetes manifests
      shell: |
        export KUBECONFIG=/home/ec2-user/.kube/config
        kubectl apply -f /home/ec2-user/deployment.yaml
      args:
        executable: /bin/bash

