- name: Deploy app to Minikube on EC2 B
  hosts: minikube
  become: yes
  tasks:

    - name: Copy Docker image tar
      copy:
        src: "{{ playbook_dir }}/../flask-app.tar"
        dest: /home/ec2-user/flask-app.tar

    - name: Load Docker image into Minikube's Docker daemon
      shell: |
        minikube ssh "docker load -i /home/docker/flask-app.tar"
      args:
        executable: /bin/bash

    - name: Copy K8s deployment file
      copy:
        src: "{{ playbook_dir }}/../k8s/deployment.yaml"
        dest: /home/ec2-user/deployment.yaml

    - name: Apply Kubernetes manifests
      shell: |
        export KUBECONFIG=/home/ec2-user/.kube/config
        kubectl apply -f /home/ec2-user/deployment.yaml

